### ISSUE TITLE
Link in contributing guideline is broken

### ISSUE THREAD

**Issue by awvwgk** [AstraZeneca/kallisto#1]
The link to the tutorial in the contributing guidelines is currently broken. See https://github.com/fortran-lang/fpm/issues/340.

> If you never created a pull request before you can learn how to do this from [this great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)

The new link to the tutorial is here:
https://app.egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github

**Comment by f3rmion** [comment]
Thanks, the link has been updated accordingly!
