### ISSUE TITLE
Python Badge Adjustment - Suggestion

### ISSUE THREAD

**Issue by Sulstice** [AstraZeneca/kallisto#11]
Add a python badge - i need to know which python versions are supported. Right now I float at python 3.7 and have been just scared about python 3.8 and above. I just need to know with what context in mind as i read the docs.

Here's some code to do so:

![Python](https://img.shields.io/badge/python-3.7-blue.svg)

**Comment by f3rmion** [comment]
[JOSS](https://github.com/openjournals/joss-reviews/issues/3050)

**Comment by awvwgk** [comment]
Doesn't this project test Python 3.8 in the GitHub actions workflow? So it's surely Python 3.8 compatible as well.

**Comment by f3rmion** [comment]
> Doesn't this project test Python 3.8 in the GitHub actions workflow? So it's surely Python 3.8 compatible as well.
Yes, Python 3.8 is tested for compatibility as well, however, the minimum Python version to apply is 3.7.

**Comment by awvwgk** [comment]
Python version badges commonly list supported Python versions explicitly rather than as lower bound:
![PyPI - Python Version](https://img.shields.io/pypi/pyversions/kallisto)

```markdown
![PyPI - Python Version](https://img.shields.io/pypi/pyversions/kallisto)
```

**Comment by f3rmion** [comment]
Ok, let's stick to the common approach then.
