### ISSUE TITLE
List links to your websites or names of people on the project. I want to see who you guys are and your style.

### ISSUE THREAD

**Issue by Sulstice** [AstraZeneca/kallisto#12]
I definitely stalk a bit,

I want to see who you guys are - like the new kids on the block.

Here's a code suggestion:

- Developer [Eike Caldeweyher](https://www.linkedin.com/in/eike-caldeweyher/)
- Developer [Philipp Pracht](https://scholar.google.com/citations?user=PJiGPk0AAAAJ&hl=de)

**Comment by f3rmion** [comment]
[JOSS](https://github.com/openjournals/joss-reviews/issues/3050)
