### ISSUE TITLE
Example Files for xyz

### ISSUE THREAD

**Issue by Sulstice** [AstraZeneca/kallisto#16]
To reach a wider audience - it would be helpful to have a wider set of example files otherwise I am digging through your test directory. 

Some folk, and I picked this up from `MDAnalysis` will come with prepared files within the package. You can choose to include yours in there for the example in the Coordination and Numbers and Sphere's page.

```

alanine-glycine.xyz

```

If someone isn't familiar with the xmol format it is also worth it to place in there as well in the docs - you could also link to the test file but most folk don't wanna flood the system with another file they have to coordinate - they like it compartmentalized.

**Comment by f3rmion** [comment]
Hi @Sulstice,

I have expanded the examples and linked to the xmol Wikipedia page.
Furthermore, I linked to the MolPol135 benchmark set that I have extracted recently from the literature.
All geometries are optimized at the CAM-B3LYP-D3(B)/def2-TZVP level of theory and available in an xmol format.
