### ISSUE TITLE
Test Section in the Feature's Pages

### ISSUE THREAD

**Issue by Sulstice** [AstraZeneca/kallisto#18]
I've ran through your First tutorial on Coordination Numbers and Sphere's for the xyz. While the output is nice and I have a general idea of what's going on I want to also know how you tested this feature right there. 

What I do for gitbook applications is split the features into three sections:

- Theory
- Implementation
- Test

So when someone looks at this feature they know how you tested it. It doesn't have to be verbose but just a "nice to have" to give me more confidence. 

If you would like I can provide a link to my unreleased gitbook to show you that.

**Comment by Sulstice** [comment]
An additional note, is this is great but what can I do with these numbers now? Which I feel will come into later applications but a good ending section for where this is used would be nice!

**Comment by f3rmion** [comment]
Hi @Sulstice,

> While the output is nice and I have a general idea of what's going on I want to also know how you tested this feature right there.

I'm not entirely sure that I understand what you exactly mean by "testing"? Is this related to unit testing or do you mean a validation that a CN really represents the count of covalent bounds for an atom in a molecule?

> An additional note, is this is great but what can I do with these numbers now? Which I feel will come into later applications but a good ending section for where this is used would be nice!

Yes, there is an application paper on the way where we use the features to predict several properties like chemical reactivity or retention times for chromatography applications. Cheers!

**Comment by f3rmion** [comment]
Hi @Sulstice,

do you think a deeper description of the atomic features is necessary? Otherwise, I'll add an additional example after publishing the application paper.

**Comment by Sulstice** [comment]
```
deeper description of the atomic features is necessary?
```

Looking back at it, no. I think you are fine. I can understand it and I'm not so much an expert in the specific area but I get what you are up too and why this is pertinent. 

This isn't really a requirement, but rather a strong opinion of mine haha. I like to read through folks units tests for things so I can improve the robustness of my own - merge tests. I'm reading through your unit tests:

```
        f.write("Pyridine" + s)
        f.write("C 1.3603 0.0256 0.0000" + s)
        f.write("C 0.6971 -1.2020 0.0000" + s)
        f.write("C -0.6944 -1.2184 0.0000" + s)
        f.write("C -1.3895 -0.0129 0.0000" + s)
        f.write("C -0.6712 1.1834 0.0000" + s)
        f.write("N 0.6816 1.1960 0.0000" + s)
        f.write("H 2.4530 0.1083 0.0000" + s)
        f.write("H 1.2665 -2.1365 0.0000" + s)
        f.write("H -1.2365 -2.1696 0.0000" + s)
        f.write("H -2.4837 0.0011 0.0000" + s)
        f.write("H -1.1569 2.1657 0.0000" + s)
```

If I read your docs, as a cheminformatician, this is just a "nice to have" tiny detail and it might or might not prove useful to me. 
For my stuff, I usually, have a list of compounds of varying complexity and try to guess what the user might input to test the robustness of my code - but I've built these test systems mimicking off RDKit, design stuff from last gig, biopandas and so on which help validate my own claims. Gives my software some backing. Does that make sense?

```
validation that a CN really represents the count of covalent bonds for an atom in a molecule

```

This part would come from the scientific community, I think, as they use your package after publication. 

```

Yes, there is an application paper on the way where we use the features to predict several properties like chemical reactivity or retention times for chromatography applications

```

Awesome! don't forget to update these docs when that comes out haha. I bet a lot of future users would appreciate it.

**Comment by f3rmion** [comment]
Hi @Sulstice,

> If I read your docs, as a cheminformatician, this is just a "nice to have" tiny detail and it might or might not prove useful to me.
> For my stuff, I usually, have a list of compounds of varying complexity and try to guess what the user might input to test the robustness of my code - but I've built these test systems mimicking off RDKit, design stuff from last gig, biopandas and so on which help validate my own claims. Gives my software some backing. Does that make sense?

It does and it is always useful to add tests depending on wrong or erroneous user input. I'll expand the unit test according to such inputs, however, this takes some time and I guess the publication of the ``software`` as it is at the moment shouldn't be postponed due to the missing tests, shouldn't it? :)

> 
> ```
> validation that a CN really represents the count of covalent bonds for an atom in a molecule
> ```
> 
> This part would come from the scientific community, I think, as they use your package after publication.
> 
> ```

From the scientific part, it has been shown in earlier works that the CN actually represent the covalent count within a molecule (see, e.g., [Grimme2010](https://aip.scitation.org/doi/full/10.1063/1.3382344?casa_token=3goW7-lZ9n8AAAAA%3AEKYjjxkPbh2Sv7o5YZn0EfAFw7gUBY4jTk-WbfFA7XvmvHzDyuqx2oFarQdi6ZlxiMFdVcojhbrU) or [ Caldeweyher2019](https://aip.scitation.org/doi/full/10.1063/1.5090222?casa_token=khn-XUMYTrwAAAAA%3AAkLMFDGAHNnKG6QS0sBYW6mEgwsQH7be8jTyhN39e3aOkTxtlXF8OlommbYUslu3gd_gBBjdXmef)).

> 
> Yes, there is an application paper on the way where we use the features to predict several properties like chemical reactivity or retention times for chromatography applications.
> ```
> 
> Awesome! don't forget to update these docs when that comes out haha. I bet a lot of future users would appreciate it.

Sure, as soon as the paper appears I'll update the docs and list some "real-life" use-cases ;)

**Comment by Sulstice** [comment]
Ya I can get behind that. Thanks for the references - helps me understand it a lot better. 

Yeah, I wouldn't postpone publication of the software for your current tests now. They are good enough for the first pass and will naturally develop over time :) I'm actually more happy you wrote some good starting tests. 

Alrighty, I think I am satisfied haha and will approve for publication.
