### ISSUE TITLE
[JOSS] grid module outside of kallisto

### ISSUE THREAD

**Issue by RMeli** [AstraZeneca/kallisto#19]
I started looking at the source code and I noticed that the `grid.py` module is outside the `kallisto` package. When `kallisto` is imported, the `grid` module also becomes available, possibly clashing with or shadowing other modules. Is this intended?

I think it would be better to have the `grid` module within the package, unless I'm missing a good reason not to.

---

[JOSS Review](https://github.com/openjournals/joss-reviews/issues/3050)

**Comment by f3rmion** [comment]
Hi @RMeli,

The Lebedev-Laikov grid is not yet available as an implemented feature. I would like to change this in the following release and also want to extend the grid further. Then I will also include it accordingly in the ``kallisto`` package as noted by you :)

**Comment by RMeli** [comment]
Thanks for the explanation @f3rmion. However, if I install `kallisto` from source, the `grid` module seem to be available:
```
>>> import grid
>>> dir(grid)
['Counter', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'genOh1', 'genOh2', 'genOh3', 'genOh4', 'genOh5', 'genOh6', 'getAngularLebedevGrid', 'gridSize', 'ld0006', 'ld0014', 'ld0026', 'ld0038', 'ld0050', 'ld0074', 'ld0086', 'ld0110', 'ld0146', 'ld0170', 'ld0194', 'np', 'z']
```

If grids are not yet available/fully implemented/supported, I think they should be removed from the installation, so that any confusion is avoided.

**Comment by f3rmion** [comment]
Hi @RMeli,

> Thanks for the explanation @f3rmion. However, if I install kallisto from source, the grid module seem to be available:

Yes, you are right it was available. I shifted the ``grid`` code to the ``kallisto`` package to overcome the clashing/shadowing problems and added unit tests respectively.

> If grids are not yet available/fully implemented/supported, I think they should be removed from the installation, so that any confusion is avoided.

In one of the next releases, I will further extend it with finer grids and add new features based on it, however, the implemented grid can be used as-is already now.
