### ISSUE TITLE
Packaging for PyPI or conda?

### ISSUE THREAD

**Issue by awvwgk** [AstraZeneca/kallisto#2]
The current toolchain to install this project is quite heavy on the user. Is there a plan to provide packaged versions of this project on a conda channel or via PyPI?

**Comment by f3rmion** [comment]
> The current toolchain to install this project is quite heavy on the user. Is there a plan to provide packaged versions of this project on a conda channel or via PyPI?

Yes indeed, there will be a PyPi package soon, which will simplify the installation process tremendously.
