### ISSUE TITLE
[JOSS] RMSD

### ISSUE THREAD

**Issue by RMeli** [AstraZeneca/kallisto#23]
In the `rmsd.py` module, it seems that there is a lot of code that could be removed in favor of `scipy.spatial.transform` and `scipy.linalg`. My view here is that code from another library is code you don't have to maintain, and a library such as `scipy` is usually very reliable, extensively tested and possibly faster.

These are the functions that could use `scipy` functionality; it would remove a lot of lines of code:
* `rotionMatrix()` could use `scipy.spatial.transform.Rotation`
   * Build a `scipy.spatial.transform.Rotation` using `from_quat()`
   * Return corresponding rotation matrix with `as_matrix()`
* `dstmev()` could be substituted with a `scipy.linalg.eigh()`?
   * This should allow the removal of `givens4`
   * If there is a good reason to implement this for scratch please let me know, I definitely missed it
* `getRodriguezRotation()` could use `scipy.spatial.transform.Rotation` internally
   * Build a `scipy.spatial.transform.Rotation` using `from_rotvec()`
   * Apply the rotation with `apply()`
* `getRotationMatrix()` could use `scipy.spatial.transform.Rotation` internally
   * Build a `scipy.spatial.transform.Rotation` using `from_rotvec()`
   * Return corresponding rotation matrix with `as_matrix()`
* `getDist` could be vectorised or substituted with `scipy.spatial.distance.euclidean` (or similar)

Up to you if you want to change these, but I think it would be helpful for future development and maintenance. The best code is no code ;)

Additionally:
* [x] The function`pythag()` is missing a docstring.
* [x] Is the definition of `unit` in `getRodriguezRotation()` correct?

---

[JOSS Review](https://github.com/openjournals/joss-reviews/issues/3050)

**Comment by f3rmion** [comment]
Hi @RMeli,

Thanks for the effort, I definitely appreciate it! Try to simplify the ``rmsd``module according to your suggestions :)

**Comment by f3rmion** [comment]
Hi @RMeli,

Things that I have changed so far (f39b577):
- add a docstring to ``pythag`` function
- fix definition of ``unit`` in ``getRodriguezRotation``
- remove unnecessary ``getRotationMatrix`` 
- replace ``getDist`` by SciPy's ``distance.euclidean``

I furthermore want to get rid of ``dstmev``, which will be covered in the next commit.

**Comment by RMeli** [comment]
Great @f3rmion . Given the two problems identified above, I think the `rmsd.py` module could do with some dedicated tests.

**Comment by f3rmion** [comment]
Hi @RMeli,

I removed ``dstmev``, ``givens4``, and ``pythag`` and replaced them with SciPy analoga.

> Great @f3rmion . Given the two problems identified above, I think the rmsd.py module could do with some dedicated tests.

Do you mean to increase the unit tests to a certain amount?

**Comment by RMeli** [comment]
@f3rmion I just noticed you used `scipy.spatial.transform.Rotation` in `getRodriguezRotation()` but not in `rotationMatrix()`. Is this on purpose or just an oversight?
