### ISSUE TITLE
Numpy Citation

### ISSUE THREAD

**Issue by Sulstice** [AstraZeneca/kallisto#25]
I would include the Numpy Citation, now that Travis published it. If you are using it in your docs and in your software, it should be mentioned. 

https://www.nature.com/articles/s41586-020-2649-2

worth a read if you haven't read it :)

**Comment by f3rmion** [comment]
Hi @Sulstice,

> I would include the Numpy Citation, now that Travis published it. If you are using it in your docs and in your software, it should be mentioned.

Yes, this should be included as well ;) I added a [Numpy](https://www.nature.com/articles/s41586-020-2649-2) and a [SciPy](https://www.nature.com/articles/s41592-019-0686-2) reference to the [docs](https://ehjc.gitbook.io/kallisto/setup).

> worth a read if you haven't read it :)

Definitely a paper I'll read in the near future.

**Comment by Sulstice** [comment]
Oh ya and to the `paper.bib` and I think that's it for me.
