### ISSUE TITLE
[JOSS] Partial Charges

### ISSUE THREAD

**Issue by RMeli** [AstraZeneca/kallisto#26]
## Documentation

In the documentation, I think the variable `chi_i` should be defined after the first formula for `E_IES` instead than within the definition of the matrix elements of `A`.

### Vectorisation

There are many places where the code can be vectorised in `getAtomicPartialCharges()`. This will speedup the execution since it will get rid of multiple `for` loops that grow linearly with the number of atoms. Some places that could benefit from vectorisation are the following:

https://github.com/AstraZeneca/kallisto/blob/293503b9d2b12ef3551fc15f50f50812bc7c2c9d/src/kallisto/methods.py#L173-L177

https://github.com/AstraZeneca/kallisto/blob/293503b9d2b12ef3551fc15f50f50812bc7c2c9d/src/kallisto/methods.py#L202-L205

https://github.com/AstraZeneca/kallisto/blob/293503b9d2b12ef3551fc15f50f50812bc7c2c9d/src/kallisto/methods.py#L207-L210

### Reshaping

I struggle to see why the arrays `A` and `X` are being reshaped

https://github.com/AstraZeneca/kallisto/blob/293503b9d2b12ef3551fc15f50f50812bc7c2c9d/src/kallisto/methods.py#L215-L216

since they have been initialized with the correct shape already. Am I missing something?

### Consistency with Documentation

Is the following line of code correct?

https://github.com/AstraZeneca/kallisto/blob/293503b9d2b12ef3551fc15f50f50812bc7c2c9d/src/kallisto/methods.py#L191

If yes, I think a few things would help understanding what is going on:

1. The name `gam` (which recalls to "gamma") is very similar to `gamij`; if I understand correctly the former represent `Jii` in the documentation and the latter is clearly `gammaij`. I'd make the variable names in the code more consistent with the documentation (or vice-versa)
2. I'd give explicitly give the definition of `gammaij` and `gammaii` in terms of the parameters `alphai` and `alphaj`; from the code there is `gamij = 1.0 / np.sqrt(alpha[i] + alpha[j])`, but then the line above seems to indicate that `gammaii = 1.0 / np.sqrt(alpha[i])` and not `gamii = 1.0 / np.sqrt(alpha[i] + alpha[i])` .

---

[JOSS Review](https://github.com/openjournals/joss-reviews/issues/3050)

**Comment by awvwgk** [comment]
> Is the following line of code correct?

Certainly correct but obscured by the fact that unrelated constants are collected in `sqrt2pi`. Most notably the 1/sqrt(2) from the evaluation of γii is merged with the 2/sqrt(π) from the paper / docs.

**Comment by RMeli** [comment]
@awvwgk thank for confirming this. In such case I think the definition of `Aii` in the documentation (and the paper?) should read `Jii + sqrt(2/π) / sqrt(alphaii)` and not `Jii + sqrt(2/π)  gammaii`.

**Comment by awvwgk** [comment]
Not quite, the paper states `Aii = Jii + 2/sqrt(π)·γii` which is equivalent to `Aii = Jii + sqrt(2/π) / αi`, special attention must be paid to the fact that the array `alpha` is actually α², see

https://github.com/AstraZeneca/kallisto/blob/293503b9d2b12ef3551fc15f50f50812bc7c2c9d/src/kallisto/methods.py#L177

**Comment by awvwgk** [comment]
I see, the formula 12 in the preprint is in error here, but the formula in the corresponding JCP paper is given correct.

**Comment by RMeli** [comment]
Thanks for pointing this out, I was indeed looking at the preprint! The [documentation](https://ehjc.gitbook.io/kallisto/features/eeq) seems to contain the same error, that's why I was confused I guess. 

Given that the preprint is linked in the documentation (which is great, since it is accessible to eveybody!) I think a note about this would be very helpful.

**Comment by f3rmion** [comment]
Hi @RMeli, Hi @awvwgk,

> I see, the formula 12 in the preprint is in error here, but the formula in the corresponding JCP paper is given correctly.

Yes, there is an error in the preprint since it should either be ``2 Jii / sqrt(π)`` or by using ``Jii = 1 / sqrt( ai² + ai²)`` to get ``sqrt(2) / ( sqrt(π) sqrt(ai²) )``. I'll add a note to the docs.

> The documentation seems to contain the same error, that's why I was confused I guess.

The docs seem to be right to me, where do you see this error? Or do you mean according to the preprint? :)

**Comment by awvwgk** [comment]
The formula is present twice in the documentation, the one in the energy expression is correct, the A matrix elements are in error.

**Comment by RMeli** [comment]
@f3rmion I think the `Aij` coefficient in the documentation for `i = j` should read `Jii + 2 / sqrt(π) * gammaii` instead of `Jii + sqrt(2/π) * gammaii`?

**Comment by f3rmion** [comment]
OK, got it and fixed it.

**Comment by f3rmion** [comment]
Hi @RMeli,

in e3c9ef2 all mentioned ``for``-loops have been vectorized and the useless reshape has been deleted. I furthermore updated the docs and added a note regarding the erroneous eq. 12 in the linked preprint. Thanks for this nice catch!

**Comment by f3rmion** [comment]
I think this can be closed.
