### ISSUE TITLE
[JOSS] Polarizabilities

### ISSUE THREAD

**Issue by RMeli** [AstraZeneca/kallisto#27]
## Documentation

> Hence the problem is shifted from calculating dynamic polarizabilities to calculating atomic coordination numbers and interpolate the atomic reference systems. This procedure comes along with a tremendous increase in efficiency and overcomes furthermore numerical issues that could occur in TD-DFT calculations.

- [x] Can you please add a comment on the accuracy of this method at this stage and link to the table?

> Note that the dynamic reference polarizabilities can be pre-scaled to, e.g., incorporate atomic-charge information as has been introduced recently by Caldeweyher et al.

- [x] Add missing reference to "Caldeweyher et al."

Other comments:
- [x] Add timing details to the table? How `kallisto` compares to `AlphaML` in terms of speed?
- [x] Add example with the `--molecular` option to compute the molecular polarizability

## Implementation

*The code is quite complex, it could do with a few more comments so that it easier to follow and understand.*

As mentioned in #26 (and for the reason above) , it would be helpful to have a better consistency between variable names in the code and the documentation. For example, you have `wf = 6.0` in the code, `beta` in the documentation (`beta` is not defined at all in the documentation) and `beta2` in the [paper](https://s3-eu-west-1.amazonaws.com/itempdf74155353254prod/7430216/A_Generally_Applicable_Atomic-Charge_Dependent_London_Dispersion_Correction_Scheme_v2.pdf). I had to dig into the paper to understand what `wf = 6.0` was.

### Vectorisation

https://github.com/AstraZeneca/kallisto/blob/293503b9d2b12ef3551fc15f50f50812bc7c2c9d/src/kallisto/methods.py#L244-L245

https://github.com/AstraZeneca/kallisto/blob/293503b9d2b12ef3551fc15f50f50812bc7c2c9d/src/kallisto/methods.py#L314-L315

There might be other parts where the code could benefit from vectorisation and some parts where loops can be reduced.

For example, here I think you can combine the two loops together:

https://github.com/AstraZeneca/kallisto/blob/293503b9d2b12ef3551fc15f50f50812bc7c2c9d/src/kallisto/methods.py#L290-L299

---

[JOSS Review](https://github.com/openjournals/joss-reviews/issues/3050)

**Comment by awvwgk** [comment]
> * Add timing details to the table? How `kallisto` compares to `AlphaML` in terms of speed?

I would be intrigued to see how the performance of `kallisto` and the reference implementation in [`dftd4`](https://github.com/dftd4/dftd4/tree/main/python) differ in terms of speed as well in such a comparison.

**Comment by f3rmion** [comment]
> > * Add timing details to the table? How `kallisto` compares to `AlphaML` in terms of speed?
> 
> I would be intrigued to see how the performance of `kallisto` and the reference implementation in [`dftd4`](https://github.com/dftd4/dftd4/tree/main/python) differ in terms of speed as well in such a comparison.

This is definitely a comparison that I'll add to the roadmap 2021, however, I'm already quite sure that the implementation with pre-combined ``dftd4`` library can't be beaten in terms of efficiency. ;)

**Comment by f3rmion** [comment]
Hi @RMeli,

> Can you please add a comment on the accuracy of this method at this stage and link to the table?

I added a comment and linked to the table, respectively.

>  Add missing reference to "Caldeweyher et al."

Another link has been added :)

>  Add timing details to the table? How kallisto compares to AlphaML in terms of speed?

I created a small benchmark set using structures from [this repository](https://github.com/f3rmion/molpol135) and calculated timings for both methods. For the ``AlphaML`` one I used the value they print out in their webinterface to get timings (CCSD mode). Here, they print out the timing to compute the quantities. I, therefore, did the same thing for ``kallisto``, but I averaged over three different runs for every molecule and used the averaged value in the final summation to obtain total computational timings.

> Add example with the --molecular option to compute the molecular polarizability

Another example is given for molecular polarizabilities using the Alanine-Glycine molecule.

**Comment by RMeli** [comment]
Nice!

> This is definitely a comparison that I'll add to the roadmap 2021, however, I'm already quite sure that the implementation with pre-compiled dftd4 library can't be beaten in terms of efficiency. ;)

That's probably true, although it would be great to see how close one can get using `numpy`/`scipy`.

**Comment by awvwgk** [comment]
It's almost an order of magnitude for me, (Skylake, Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz). Conda-forge's Python, Scipy and MKL (average over 5 runs for the 45 systems from the docs):

1: `kallisto` CLI -> 15.4s user, 9.1s system
2: `dftd4` CLI -> 2.3s user, 0.4s system
3: `dftd4` Python API > dftd4.out -> 0.4s user, 0.2s

Looks like the task in docs could be bound by launching the processes.

**Comment by f3rmion** [comment]
Thanks, @awvwgk! I'll update the docs with your timings then :)

**Comment by RMeli** [comment]
@f3rmion LGTM. One last thing; could you please move the following

> MAD = Mean Absolute Deviation; MD = Mean Deviation; RMSD = Root-Mean Squared Deviation; AMAX = Absolut MAXimum deviation. 

just after the first table? I think it will help to better separate the two tables and avoid any confusion (`dftd4` being aligned with the MP2 column).

**Comment by f3rmion** [comment]
Hi @RMeli,

> just after the first table? I think it will help to better separate the two tables and avoid any confusion (dftd4 being aligned with the MP2 column).

Done :)
