### ISSUE TITLE
[JOSS] Van der Waals Radii

### ISSUE THREAD

**Issue by RMeli** [AstraZeneca/kallisto#28]
## Documentation

The following docstring is incorrect:

https://github.com/AstraZeneca/kallisto/blob/293503b9d2b12ef3551fc15f50f50812bc7c2c9d/src/kallisto/methods.py#L383-L390

### Vectorisation

Unfortunately I think that changes introduced for https://github.com/AstraZeneca/kallisto/issues/22 prevent vectorisation in this case (sorry for not spotting this previously!), since you have to go from the atomic number to the chemical symbol in order to extract the parameters needed.

https://github.com/AstraZeneca/kallisto/blob/293503b9d2b12ef3551fc15f50f50812bc7c2c9d/src/kallisto/methods.py#L406-L408

I'm not too keen to suggest to revert the changes, so it is up to you to decide if it is worth the effort.

---

[JOSS Review](https://github.com/openjournals/joss-reviews/issues/3050)

**Comment by f3rmion** [comment]
Hi @RMeli,

> The following docstring is incorrect:

I updated the docstring to get rid of the copy-paster error.

> I'm not too keen to suggest to revert the changes, so it is up to you to decide if it is worth the effort.

Yes, at the moment I don't see that it's worth the effort.
