### ISSUE TITLE
[JOSS] Sterimol Descriptors

### ISSUE THREAD

**Issue by RMeli** [AstraZeneca/kallisto#30]
# Documentation

The documentation for the sterimol descriptors is quite scarce. I'd add some details (or at very least link to the relevant section of the [Morfeus package](https://kjelljorner.github.io/morfeus/sterimol.html).

# Code

Do I understand correctly that the code comes directly from [Morfeus package](https://kjelljorner.github.io/morfeus/sterimol.html)? I would make this clearer in the module docstring (not only the function `getClassicalSterimol()`). Is there any kind of copyright or license that needs to be mentioned as well?

I was not able to find this code; if it was given in private, maybe an acknowledgment of this in the paper is needed. Some clarifications about how the code was obtained and integrated would be helpful to better understand the situation.

---

[JOSS Review](https://github.com/openjournals/joss-reviews/issues/3050)

**Comment by f3rmion** [comment]
Hi @RMeli,

> The documentation for the sterimol descriptors is quite scarce. I'd add some details (or at very least link to the relevant section of the Morfeus package.

I will expand the documentation accordingly so that the main aspect of the Sterimol descriptors becomes clear.

> Do I understand correctly that the code comes directly from Morfeus package? I would make this clearer in the module docstring (not only the function getClassicalSterimol()). Is there any kind of copyright or license that needs to be mentioned as well?
> I was not able to find this code; if it was given in private, maybe an acknowledgment of this in the paper is needed. Some clarifications about how the code was obtained and integrated would be helpful to better understand the situation.

The Morfeus code is not yet published, which will change in the near future (open source). The code is not directly taken from this package, however, the algorithm has been adapted (therefore the mentioning). When I asked him the last time he only wanted a note in the docs, but I'll definitely add an acknowledgment to the paper ;)

**Comment by RMeli** [comment]
Thanks for the clarifications @f3rmion !

**Comment by f3rmion** [comment]
Hi @RMeli,

I added an acknowledgment to the paper (17429a2) and extended the [docs](https://ehjc.gitbook.io/kallisto/features/stm) with an explanation of what Sterimol descriptors are.

**Comment by RMeli** [comment]
@f3rmion LGTM
