### ISSUE TITLE
[JOSS] Tests

### ISSUE THREAD

**Issue by RMeli** [AstraZeneca/kallisto#31]
Most of the tests are in `test_cli.py` instead of being in separate and standalone files (for example `test_methods.py`, `test_rmsd.py`, ...). This is not a problem in itself, but it seems that in some tests the `assert`s do not really check the result.

Using the CLI to perform tests forces you to check the results as strings instead of numbers. This seems to be done incorrectly (see below). Additionally, if at some point you want to change the output format (for example to use scientific notation), you will have to change all the assertions.

I would suggest to re-work the tests in order to decouple the test of the CLI from the tests of the functionality. This is not really necessary, but the feeling I have looking at `test_cli.py` is that the code coverage is very high because all parts of the code are run while some tests are not really meaningful (i.e. they mostly check that the test was run and output files have been created). I can't see many tests for edge cases either.  I would like to see more clear and meaningful tests, comparing with known results (obtained from reference software or from manual calculations), so that users can make sure the package produces correct numerical results.

# `testcli.py`

## Tests without output?

The following tests does not seem to have any output when run outside the testsuite:

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L96-L104

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L107-L115

## Test checking only if output files have been produced

The following tests only check if files have been produced, but not the content of the output file and there is no check beside the fact that they run:

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L118-L133

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L418-L433

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L730-L745

## Incorrect assertions

The following assertions look incorrect, since `"A" and "B"` evaluates to `"B"` if `"A"` is true (i.e. non-empty string):

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L202 

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L214

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L226

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L250

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L262

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L274

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L310

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L322

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L336

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L350

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L364

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L378

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L459

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L471

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L1182-L1186

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L1236

# Additional Comments

The following test brought to my attention that the original information in the second line of the XYZ file is lots and replaced by "Created with kallisto":

https://github.com/AstraZeneca/kallisto/blob/fe8496349b48f80c2b5af41e9754b87aef932569/tests/test_cli.py#L175-L178

I think it would be better to retain the original comment and add "Created with kallisto" after it.

---

[JOSS Review](https://github.com/openjournals/joss-reviews/issues/3050)

**Comment by RMeli** [comment]
Maybe it is worth merging `test_xyz.py` into `test_strucreader.py` since `strucreader.py` deals with both XYZ and Turbomole input?

**Comment by RMeli** [comment]
Most tests seems to re-define the same file. Probably it is worth using [fixtures](https://docs.pytest.org/en/stable/tmpdir.html#the-tmpdir-factory-fixture)? 

This should also get rid of the problems in #32 (hopefully), if you are keen to support all platforms.

**Comment by f3rmion** [comment]
> Most tests seems to re-define the same file. Probably it is worth using [fixtures](https://docs.pytest.org/en/stable/tmpdir.html#the-tmpdir-factory-fixture)?
> 
> This should also get rid of the problems in #32 (hopefully), if you are keen to support all platforms.

At the moment I am working on separating all the tests regarding the functionality of the CLI and numerical tests. So soon there will be no more string comparisons. When this is finished, I will take care of providing the CLI unit tests (which need files) with a corresponding fixture, so that Windows, among others, also gets the corresponding support.

**Comment by f3rmion** [comment]
Hi @RMeli,

I replaced all ``tempfile.NamedTemporaryFile`` with files in temporary directories (using ``tmpdir_factory`` and fixtures) and (after some strange errors that I've fixed) it is now working. You can try to extend the platform support now.

**Comment by RMeli** [comment]
@f3rmion There are still a few `tempfile.NamedTemporaryFile` in `test_molecule.py` and `test_structreader.py` as far as I can see. I can take care of them as part of #32 if you want (since they are making the Windows CI fail).

**Comment by f3rmion** [comment]
> @f3rmion There are still a few `tempfile.NamedTemporaryFile` in `test_molecule.py` and `test_structreader.py` as far as I can see. I can take care of them as part of #32 if you want (since they are making the Windows CI fail).

That's correct I missed those. Just add them to your PR then 👍

**Comment by f3rmion** [comment]
Hi @RMeli,

most of the tests have now explicit checks against numerical values. The CLI tests check only if everything runs smoothly through without any error. I guess the suggestion of using fixtures was really good since the unit tests are cleaner now. I furthermore added some new tests that, e.g., check for implemented options (cns and vdw). The ``turbomole`` and ``xyz`` tests are now in the ``strucreader`` as well. The input of created constrainment files are now checked as well. Do you think this issue can be closed, or is something still missing?

**Comment by RMeli** [comment]
@f3rmion Thanks for changing the tests to be more explicit and robust! I know it was a lot of work, but I think it was well worth going forward.

For a skim trough they look very good, but I'll have a deeper look in the coming days and update or close this issue. I hope to finish the whole review this weekend at the latest.

One thing I noticed skimming through them is that assertions like the following should have an absolute value:
https://github.com/AstraZeneca/kallisto/blob/58602bd713d8e989b631eee7722514eadd04e9ca/tests/test_eeq.py#L13-L14

Maybe it would be even better to use [`math.isclose`](https://docs.python.org/dev/library/math.html#math.isclose) and [`numpy.isclose`](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html)

**Comment by f3rmion** [comment]
Good suggestion, I go with ``numpy.isclose`` then.

**Comment by RMeli** [comment]
Thanks for the hard work on refactoring the whole test framework! LGTM!

When excluding the CLI from the tests the coverage is still very high:
```
---------- coverage: platform darwin, python 3.7.10-final-0 ----------
Name                                 Stmts   Miss Branch BrPart  Cover   Missing
--------------------------------------------------------------------------------
src/kallisto/__init__.py                 1      0      0      0   100%
src/kallisto/atom.py                    51      4     12      2    90%   20, 29, 32, 77, 90->exit
src/kallisto/console.py                208    208     42      0     0%   3-579
src/kallisto/data/__init__.py           10      0      2      0   100%
src/kallisto/data/alpha.py            7755      0      0      0   100%
src/kallisto/data/vdw.py                 2      0      0      0   100%
src/kallisto/grid.py                  1412      1      6      2    99%   92->exit, 106
src/kallisto/methods.py                270      5    108      6    97%   36, 58, 82, 129, 344, 403->412
src/kallisto/molecule.py               125      6     50      6    92%   56->58, 58->61, 66, 89-92, 124, 138
src/kallisto/reader/__init__.py          0      0      0      0   100%
src/kallisto/reader/strucreader.py      33     11     10      4    60%   13-22, 38, 40->45, 41->40, 53-56
src/kallisto/reader/turbomole.py        19      0      8      2    93%   23->27, 27->39
src/kallisto/reader/xyz.py              14      0      2      0   100%
src/kallisto/rmsd.py                   268     19     70      9    91%   146, 250, 302, 328->332, 364, 389->397, 412-420, 436-441, 457-458
src/kallisto/sort.py                    30     30      6      0     0%   4-66
src/kallisto/sterics.py                 41      3      4      1    87%   38-40
src/kallisto/units.py                   48      2      0      0    96%   53-54
src/kallisto/utils/__init__.py          13      6      2      0    47%   14-15, 20-21, 26-27
src/kallisto/utils/alpha.py              8      1      2      1    80%   10
--------------------------------------------------------------------------------
TOTAL                                10308    296    324     33    96%
```
