### ISSUE TITLE
Is there any more documentation for the sterimol descriptors?

### ISSUE THREAD

**Issue by Montana** [AstraZeneca/kallisto#33]
As the title suggests, is there any more in depth documentation on sterimol descriptors? Thank you so much.

-Montana Mendy

**Comment by f3rmion** [comment]
Hi @Montana,

As you surely already check out the [docs](https://app.gitbook.com/@ehjc/s/kallisto/features/stm) give a short overview about the Sterimol descriptors. Papers that cover the theory behind the scenes are, e.g., [[1]](https://www.sciencedirect.com/science/article/pii/B9780120603077500109?via%3Dihub) and [[2]](https://www.sciencedirect.com/science/article/pii/B9780080292229500512?via%3Dihub) - unfortunately both are not open access. More in depth documentation is at the moment not available. I plan to augment the docs with an API documentation as well, but I need to find the time to do this properly. 

What is missing from your point of view to get started?

Cheers Eike

**Comment by Montana** [comment]
Hey @f3rmion, 

It was more just a query of curiosity. I appreciate your quick response. 

Thank you, 
Montana Mendy
