### ISSUE TITLE
[JOSS] Installation instructions

### ISSUE THREAD

**Issue by RMeli** [AstraZeneca/kallisto#8]
Installation with `pip` works flawlessly in a clean `conda` environment.

Installation from source also works flawlessly, but I think the instructions could be simplified so that users can choose how to manage their environments. For example, `poetry` is also available on the `conda-forge` channel and `nox` can be installed using `conda` instead of `pip`. 

I suggest to decouple the installation instructions for of Python and dependencies from the installation of `kallisto` as follows:

- [x] Clearly state the dependencies to install from source (`poetry`, Python version, ...)
    - [x] Link to the installation instructions of such dependencies
- [x] Simplify the instructions to install `kallisto`: clone, change directory, call potery
- [x] Create a separate section for testing
    - [x] List dependencies for testing (`nox`)

The advantage of linking to the installation instructions of the dependencies, IMHO, is that you won't need to maintain such instructions up to date yourself and users can install such dependencies in their preferred way (`conda` vs `pip`, ...).

Additional comments/questions:

- [x] Is "The Verbose Mode" section intended to be in the installation page?
- [ ] It would also be nice to have a list of the main dependencies at the top of the installation page.

---

[JOSS Review](https://github.com/openjournals/joss-reviews/issues/3050)

**Comment by f3rmion** [comment]
Hi @RMeli,

This is a very good suggestion. I have already changed the [kallisto docs](https://ehjc.gitbook.io/kallisto/setup) accordingly. 
Now all dependencies are listed and the installation process from the source is simplified. I also added a [testing suite](https://ehjc.gitbook.io/kallisto/test) section that lists all nox sessions for unit test purposes. I furthermore shifted the "Verbose mode" and "Need help" to [misc](https://ehjc.gitbook.io/kallisto/misc/help). Once you approve this, I will also update the README.md within the kallisto repository.

**Comment by RMeli** [comment]
@f3rmion Looks very good now, I like the separated and expanded section for the test suite! The last comment I have is about the list of dependencies: I think it is a bit difficult to read now and it seems that most dependencies are related to development. 

- [ ] Would it be possible to just list the main dependencies needed to run the scripts? 

You could link to the `project.toml` file for further details, where the distinction between dependencies and development dependencies is very clear (on this note: is `flake8` supposed to be under both `[tool.poetry.dependencies]` and `[tool.poetry.dev-dependencies]`?).

**Comment by f3rmion** [comment]
@RMeli I further condensed the dependencies to the core (main dependencies) and removed ``flake8`` from ``tool.poetry.dependencies`` (d8420d8).
